

Vagrant.configure("2") do |config|

  # VM1 configuration (shared server)
  # List of VM names to extend VM1 confgurations to 3 machines
  vm_names = ["vm1_v1", "vm1_v2", "vm1_v3"]

  vm_names.each do |name|
    config.vm.define name do |vm|
      vm.vm.box = "bento/ubuntu-24.04"
      # Network: dynamic IP
      vm.vm.network "public_network"
    
      # Shared folder between host and VM
      vm.vm.synced_folder "./shared", "/home/vagrant/shared"
    
      # Provisioning with inline shell script
      vm.vm.provision "shell", inline: <<-SHELL
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install -y curl wget git
      SHELL
    
      # Parallels provider configuration for VM1
      vm.vm.provider "parallels" do |prl|
        prl.memory = 2048  # 2GB RAM
        prl.cpus = 2       # 2 CPU
      end
    end

  # VM2 configuration (private server) 
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-24.04"  # or "generic/debian12"

    # Network: static IP (via DHCP in private network)
    vm2.vm.network "private_network", type: "dhcp"

    # Shared folder between host and VM
    vm2.vm.synced_folder "./shared", "/home/vagrant/shared"

    # Provisioning with an external shell script
    vm2.vm.provision "shell", path: "setup.sh"

    # Parallels provider configuration for VM2
    vm2.vm.provider "parallels" do |prl|
      prl.memory = 2048  # 2GB RAM
      prl.cpus = 2       # 2 CPU
    end
  end

  # VM3 configuration (public server with static IP)
  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "bento/ubuntu-24.04"  # або "generic/debian12"

    # Network: public network with a static IP
    vm3.vm.network "public_network", 
                   bridge: "en0", # Use your host network interface (e.g., Wi-Fi or Ethernet)
                   ip: "192.168.1.100"  # Static IP address for the VM

    # Shared folder between host and VM (separate shared folder for VM3)
    vm3.vm.synced_folder "./shared_vm3", "/home/vagrant/shared"

    # Provisioning with an inline shell script
    vm3.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt install -y curl wget git
    SHELL

    # Parallels provider configuration for VM3
    vm3.vm.provider "parallels" do |prl|
      prl.memory = 2048  # 2GB RAM
      prl.cpus = 2       # 2 CPUs
      end
    end
  end

end
